### ISSUE TITLE
Amazon Elastic Network Adapter 

### ISSUE THREAD

**Issue by jonathanstrong** [ixy-languages/ixy.rs#1]
I'm interested in userspace access to the network device, and my codebase is in rust, but this would be my first go at it. Would it be possible to get ixy to work with the AWS virtual network driver (ENA)? I'm aware there is a [DPDK driver](https://github.com/amzn/amzn-drivers/tree/master/userspace/dpdk). Just looking for your top-level advice on whether this is doable, and possibly pointing me in the right direction on how to figure it out. 

Also, when you say this code is not production ready, can you elaborate? What is it lacking? What could go wrong?

**Comment by ackxolotl** [comment]
This should be a feasible task if there is a DPDK driver already, although it is generally easier when there is a programmer's manual available (like it is for the Intel ixgbe family) since understanding DPDK's code might be challenging. Have a look at the source code of the ENA DPDK driver, especially `ena_ethdev.c`: https://github.com/DPDK/dpdk/tree/master/drivers/net/ena

Regarding productivity: The packet interface is very basic, there is no network stack whatsoever and the driver supports far less hardware offloading features than DPDK does. Besides, the driver has to be executed with root privileges to be able to access the PCIe device (which can only be effectively remedied by making use of the IOMMU).

Regarding risks: Well, the general problem is that the network card can write to any physical addresses provided by the network driver. If there is a flaw in our implementation, the card might corrupt your system by overwriting vital parts (for example data structures of your file system).

Because of these points the driver is not production ready. Nevertheless, our implementation shows that network drivers can be written in Rust and that they are efficient :-)

If you are generally interested in Rust network drivers, have a look at the e1000 and rtl8168 implementations from Redox:
https://github.com/redox-os/drivers/tree/master/e1000d/src
https://github.com/redox-os/drivers/tree/master/rtl8168d/src
