### ISSUE TITLE
Unable to ssh into VM

### ISSUE THREAD

**Issue by govardhangdg** [ixy-languages/ixy.rs#22]
Hello @ackxolotl! I am trying to run the code. After creating the VM's using the provided `Vagrantfile`, I am not able to ssh into them. When I run `vagrant ssh pktgen`, I receive
> ssh_exchange_identification: read: Connection reset by peer

Can someone help me with this?
Thanks.

**Comment by govardhangdg** [comment]
The output on the other side, (where I have run `vagrant up pktgen`):
> vagrant up fwd
Bringing machine 'fwd' up with 'virtualbox' provider...
==> fwd: Importing base box 'debian/buster64'...
==> fwd: Matching MAC address for NAT networking...
==> fwd: Checking if box 'debian/buster64' version '10.3.0' is up to date...
==> fwd: Setting the name of the VM: ixy_fwd_1583645910926_70863
==> fwd: Clearing any previously set network interfaces...
==> fwd: Preparing network interfaces based on configuration...
    fwd: Adapter 1: nat
    fwd: Adapter 2: intnet
    fwd: Adapter 3: intnet
==> fwd: Forwarding ports...
    fwd: 22 (guest) => 2222 (host) (adapter 1)
==> fwd: Running 'pre-boot' VM customizations...
==> fwd: Booting VM...
==> fwd: Waiting for machine to boot. This may take a few minutes...
    fwd: SSH address: 127.0.0.1:2222
    fwd: SSH username: vagrant
    fwd: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.
If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.
If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.
If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

But no matter what value the `timeout` value is, the ssh connection doesn't get through.

**Comment by govardhangdg** [comment]
UPDATE: I tried using the vagrant file from the https://github.com/emmericp/ixy project. I was able to successfully ssh into the VM this time. I installed rust tools and cloned this repo and built it. But when I tried to run any example, I receive the error 
> 2020-03-08 06:36:46,573 DEBUG [ixy::virtio] configuring bar0
2020-03-08 06:36:46,575 DEBUG [ixy::virtio] device features: 1000001000011111101110110100011
2020-03-08 06:36:46,576 DEBUG [ixy::virtio] device features:   01000001000011111101110110100011
2020-03-08 06:36:46,577 DEBUG [ixy::virtio] required features: 00001000000001100000000000100011
thread 'main' panicked at 'device does not support all required features', src/virtio.rs:112:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

How can I allow additional features to the `virtio` device? 
Thanks.

**Comment by Bobo1239** [comment]
Regarding the ixy.rs Vagrantfile: Seems like there was was a regression in VirtualBox with its Virtio support. (It worked around October 2019.) On my (Arch Linux) machine using either host-only/internal networking or the Virtio NIC works. But using them in conjunction breaks any networking from the VM. Unfortunately I'm not sure what exactly is going wrong... (FWIW the Vagrantfile from [emmericp/ixy](https://github.com/emmericp/ixy) also doesn't work for me atm...)

Regarding the missing feature bits: VirtualBox doesn't support `VIRTIO_F_ANY_LAYOUT` which we're currently using to make our implementation a bit simpler. I have [a patch](https://github.com/Bobo1239/ixy.rs/commit/77ef59c7bea047374f96d8004c330b4195fb6042) sitting around which enables VirtualBox support. If you want you can cherry-pick it and give it a whirl. (IIRC there was a performance issue with it (either because of the patch or because of VirtualBox) but I can't test it atm with the broken VirtualBox networking...)

If you're running Linux and don't require VirtualBox I'd suggest trying out Vagrant + libvirt which works more reliably in my experience (although NFS shared folders are broken on my machine...):
```
vagrant plugin install vagrant-libvirt
vagrant up --provider=libvirt
```

**Comment by emmericp** [comment]
VirtualBox's VirtIO support is unfortunately pretty.... basic. And sometimes buggy. And always slow :(

You'll have more luck with a KVM-based VM, e.g. with the libvirt provider. Our CI runs on KVM VMs
