### ISSUE TITLE
is IxgbeRxQueue concurrent?

### ISSUE THREAD

**Issue by lagudomeze** [ixy-languages/ixy.rs#3]
fn rx_batch(
        &mut self,
        queue_id: u32,
        buffer: &mut VecDeque<Packet>,
        num_packets: usize,
    )

is there someting to guard by &mut self?

**Comment by emmericp** [comment]
Device queues are single procuder single consumer by design in all fast drivers; the programming model is usually one hardware queue per IO thread. The 82599 NICs targeted here offer 128 or 64 queue pairs for this reason. More modern NICs usually have far more queue pairs (768 or more) for this reason.

So: no, it's not meant to be concurrent.
